### ISSUE TITLE
Logging operator's fluentd instances not printing logs to stdout

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [sighupio/fury-kubernetes-logging#113]
# Problem
By default, the logging operator configures Fluentd to print logs in a file inside the container.

When doing troubleshooting activities, those logs are not available in Kibana/Loki nor by querying them with `kubectl logs` or `stern`. The only way is to use `kubectl exec` to enter inside the pod and print the file to stdout. e.g.:
```bash
kubectl exec -it logging-demo-fluentd-0 cat /fluentd/log/out
```

# Proposed solution
As said in the documentation, we should add the stdout filter in `Flow` and `ClusterFlow` resources :
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
  name: kubernetes
  namespace: logging
spec:
  filters:
  - stdout: {}
```
## Additional information
- Affected versions: `>= 2.0.0`
## References
- [Logging operator: Get fluentd logs ](https://banzaicloud.com/docs/one-eye/logging-operator/operation/troubleshooting/fluentd/#get-fluentd-logs)
- [Logging operator: Set stdout as an output](https://banzaicloud.com/docs/one-eye/logging-operator/operation/troubleshooting/fluentd/#set-stdout-as-an-output)
